// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cis174GameWebSite.Data;

namespace cis174GameWebSite.Migrations
{
    [DbContext(typeof(HighScoreDbContext))]
    [Migration("20191202211614_updatedHighScoreUserId")]
    partial class updatedHighScoreUserId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cis174GameWebSite.Models.HighScoreViewModel", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Score");

                    b.Property<string>("UserId");

                    b.HasKey("ScoreId");

                    b.ToTable("HighScoreViewModel");
                });
#pragma warning restore 612, 618
        }
    }
}
